---
title: "QC overview. Boring but relevant"
---
aims:

```{r}
library(tidyverse)
library(rstatix)
library(ggrepel)
#read the data
data<-readxl::read_excel("data/227_0001_01_UTHSA_Report.xlsx",sheet = "Proteins")
#the :: operator allows you to use function read_excel from library readxl without loading the library
```

# General overview of the table
```{r}
colnames(data)%>%view()# to see column names in a new tab
dim(data)#to see data size
#dim(data)
#[1] 10457    99
#the 1st number is the row size, the 2nd is the column size

data%>%
  select(SeqID:Gene)%>%#to see from column SeqID to column Gene
  apply(2,function(x) #apply to every column (represented by x) the function in line 27
    #2 means columns, 1 would run over rows
  length(unique(x)))# length of a set with the non duplicated values from column x
#  SeqID Uniprot    Gene 
#  10457    9389    9580 
#SeqID has unique identifiers
```
## Check variables in rows (proteins, genes, whatever is in your table )
```{r}
mat<-data%>%select(Counts_BEME004_Control_Control_NA:
                     Counts_Test00005_Endometriosis_NA_NA)%>%
  as.matrix()
#to have duplicated gene names
rownames(mat)<-make.names(data$Gene,unique = 1)
#adds X at the beginning of gene names that start with number
#adds .1,.2,... at the end of duplicated genes

#check the average value for all probes
temp<-tibble(avg=rowMeans(mat))
temp%>%ggplot(aes(x=avg))+geom_histogram()+scale_x_log10()+
  ggtitle("Average signal distribution")
#which features should be filtered out
temp%>%mutate(gene=rownames(mat))%>%filter(avg<100)

#check the distribution per type of sample
temp<-data.frame(sample=colnames(mat),
                 type=str_split_i(colnames(mat),pattern = '_',i = 3))
temp1<-temp%>%split(f = temp$type)%>%
  sapply(function(x) rowMeans(mat[,x$sample]))
temp1<-temp1%>%as.data.frame()%>%mutate(gene=rownames(mat))%>%
  pivot_longer(-gene,names_to = "type",values_to = "avg")
temp1%>%ggplot(aes(x=type,y=avg))+geom_boxplot()+
  geom_text_repel(data=temp1%>%group_by(type)%>%
                    slice_min(avg,n = 2),aes(x=type,y=avg,label=gene))+
  geom_text_repel(data=temp1%>%group_by(type)%>%
                    slice_max(avg,n = 3),aes(x=type,y=avg,label=gene))+
  scale_y_log10()
```

## PCA
```{r}
pcares<-mat%>%
  log()%>%#log transform the data to stabilize the variance
  t()%>%#transpose the matrix
  prcomp(scale. = T)#pca
temp<-pcares$x%>%as.data.frame()#to get the coordinates of the samples in the dimension reduced space

#there are as many components as samples
ncol(mat)==ncol(temp)
#for elbow plot
data.frame(var_percent=100*pcares$sdev**2/sum(pcares$sdev**2),
           pc=1:length(pcares$sdev))%>%
  ggplot(aes(x=pc,y=var_percent))+geom_col()
#you need 15 components to explain 50% of data variances

temp<-temp%>%
  rownames_to_column("sample")%>%#opposite to column_to_rownames
  mutate(type=str_split_i(sample,pattern = "_",i = 3))#create a new column named type by splitting sample names at every "_" an keeping the 3rd value 
temp%>%ggplot(aes(x=PC1,y=PC2,col=type))+#to color by the new type column
  geom_point()+#for scatterplot
  geom_text_repel(data=temp%>%slice_min(PC2,n = 3),
                  aes(x=PC1,y=PC2,label=sample))+
  geom_text_repel(data=temp%>%slice_min(PC1,n = 3),
                  aes(x=PC1,y=PC2,label=sample))
#spot the outlier

#you can check if any of the PCs separates the groups
testres<-temp%>%
  pivot_longer(PC1:PC85,names_to = "comp",values_to = "variate")%>%
  group_by(comp)%>%
  wilcox_test(variate~type)
testres%>%filter(p.adj<0.05)

#lack of clustering indicates too much noisy proteins
i<-which(abs(data$Log2FC_LApos.LAneg)>=1)
pcares<-mat[i,]%>%
    log()%>%#log transform the data to stabilize the variance
    t()%>%#transpose the matrix
    prcomp(scale. = T)#pca
temp<-pcares$x%>%as.data.frame()
temp%>%
    rownames_to_column("sample")%>%#opposite to column_to_rownames
    mutate(type=str_split_i(sample,pattern = "_",i = 3))%>%
    ggplot(aes(x=PC1,y=PC2,col=type))+#to color by the new type column
    geom_point()
```

# Add metadata
```{r}
meta<-read_tsv("data/somamer_cohort_demographics")
temp<-as.data.frame(cbind(Sample=colnames(mat),
                          subject_id=str_split_i(colnames(mat),"_",i = 2)))
#check mismatches
temp[!temp$subject_id%in%meta$subject_id,]
#85 Counts_Test00005_Endometriosis_NA_NA  Test00005
#homogenize subject_id
meta<-meta%>%mutate(subject_id=str_replace(subject_id," ","0"))
#temp[!temp$subject_id%in%meta$subject_id,]# empty now
meta<-meta%>%left_join(temp)

#maker tge data columns order match metadata
mat<-mat[,meta$Sample]

#example plot
temp<-mat%>%t()%>%as.data.frame()%>%rownames_to_column("Sample")
temp%>%select(Sample,IL32)%>%left_join(meta)%>%
  ggplot(aes(x=race2,y=IL32))+geom_violin()+
  geom_jitter(wdith=.1)+geom_boxplot(width=.1)+
  theme(axis.text.x=element_text(angle=45,vjust = 1,hjust = 1))+
  stat_compare_means(label='p.signif',ref.group = "White")
#enough non white patients to see differences?
```

# Differential expression
```{r}
#Is limma really correct for this tye of data?
library(limma)

#limma doesn't like spaces/complex names
meta<-meta%>%mutate(AltCategory=str_replace(Category," ","_")%>%
                      str_replace("-$","neg")%>%
                      str_replace("\\+$","pos"),
                    assumed_phase=replace_na(assumed_phase,"unknown"))

#set up themodel to fit 
designM<-model.matrix(~0+assumed_phase+AltCategory,data=meta)
#report says data is log transformed but range is too wide so
voomres<-voom(mat,design = designM,plot = T)#optional normalization
#best correlation with supplied LFC for LA+vsLA- (.939 vs .938)
#padj corr with either log10,log2,voom or raw is tiny and significant

#linear model considering the variable in the matrix
fit<-lmFit(voomres,designM)
#compare variables as named in the design matrix
cont<-makeContrasts(assumed_phasefollicular-assumed_phaseluteal,
                    levels = designM)
fit<-contrasts.fit(fit,cont)
# test: treat is better, ebayes is less strict?
fit <- eBayes(fit, robust=TRUE)
#diffrential results per gene
res<-topTable(fit,number = nrow(mat),coef = 1)

```

# Check expression by sample
```{r}
summary(mat)#statistics about value distribution for the sample

#like summary but visual
temp<-temp%>%rownames_to_column("SeqID")%>%
  pivot_longer(-1,names_to = "sample",values_to = "raw_value")
temp%>%ggplot(aes(x=sample,y=raw_value))+
  geom_boxplot()+
  scale_y_log10()+
  theme(axis.text.x = element_text(angle=45,vjust = 1,hjust = 1))#otherwise samplenames will be horizontal and unreadable
#samples with really different distributions may be a red flag

#you can check distributions are not significantly different but this is slow
#run it for some samples
temp%>%
  wilcox_test(raw_value~sample,#test expression by sample
              ref.group ="Counts_BEME025_Endometrioma_Endometrioma_NA")#arbitrary reference
#there are better test for this, what did they used for the report?
```
# top genes per contrast
```{r}
#to check the changes between conditions
temp<-data%>%select(Gene,Log2FC_LApos.LAneg,
              Log2FC_Endometrioma.Control,
              Log2FC_Endometriosis.Control,
              Log2FC_EDTA.CPT)
temp%>%select(-1)%>%summary()#numeric result
temp<-temp%>%pivot_longer(-1,names_to = "contrast",values_to = "LFC")
#visual result (same idea than volcano, more space efficient, can show shared genes)
temp%>%ggplot(aes(x=contrast,y=LFC))+geom_boxplot()+
  geom_text_repel(data = temp%>%group_by(contrast)%>%slice_max(abs(LFC),n=10),
              #label top 10 altered genes
                  aes(x=contrast,y=LFC,label=Gene))

# check expression distribution for some genes
temp<-data%>%filter(Gene%in%c("CRDL2","SAA"))%>%
  select(SeqID,Gene,Counts_BEME004_Control_Control_NA:Counts_Test00005_Endometriosis_NA_NA)%>%
  pivot_longer(-1,names_to = "sample",values_to = "expr")%>%
  mutate(sampletype=str_split_i(sample,pattern = "_",i = 3),
         Gene=paste0(Gene,":",SeqID))
temp%>%
  ggplot(aes(x=sampletype,y=expr))+geom_violin()+geom_boxplot(width=.1)+
  scale_y_log10()+facet_grid(~Gene)+
  theme(axis.text.x = element_text(angle=45,vjust = 1,hjust = 1))+
  stat_compare_means(label = "p.signif",
                     comparisons = list(c("Control","Endometrioma"),
                                        c("Control","Endometriosis"),
                                        c("Control","EndometriosisLAneg"),
                                        c("Control","EndometriosisLApos")))
temp%>%distinct(sample,sampletype)%>%count(sampletype)
```

# Does enrichment make sense with this type of data?
```{r}
temp<-data%>%select(Gene,Log2FC_EDTA.CPT,Log2FC_Endometriosis.Control,
                    Log2FC_Endometrioma.Control,Log2FC_LApos.LAneg)%>%
  pivot_longer(-1,names_to = "contrast",values_to = "LFC")
ranks<-temp%>%split(f = temp$contast)%>%lapply(function(x) 
  x%>%drop_na()%>%group_by(Gene)%>%slice_max(LFC)%>%arrange(desc(LFC))%>%
    select(-contast)%>%deframe)

#find appropiate db for this ids
gseares<-lapply(ranks,function(x) 
  gseGO(geneList = x,keyType = "SYMBOL",ont="BP",OrgDb = 'org.Hs.eg.db'))
sapply(gseares,nrow)
```